version: '3.8'
services:
    oai-gnb:
        image: oai-gnb:latest
        privileged: true
        container_name: magma-oai-gnb
        environment:
            RFSIMULATOR: server
            USE_SA_TDD_MONO: 'yes'
            GNB_NAME: gnb-rfsim
            TAC: 1
            MCC: '724'
            MNC: '99'
            MNC_LENGTH: 2
            NSSAI_SST: 1
            NSSAI_SD0: 'FFFFFF'
            NSSAI_SD1: 112233
            AMF_IP_ADDRESS: 192.168.60.176
            GNB_NGA_IF_NAME: enp0s8
            GNB_NGA_IP_ADDRESS: 192.168.60.154
            GNB_NGU_IF_NAME: enp0s8
            GNB_NGU_IP_ADDRESS: 192.168.60.154
            USE_ADDITIONAL_OPTIONS: --sa -E --rfsim --log_config.global_log_options level,nocolor,time
        network_mode: host
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue:
        image: oai-nr-ue:latest
        privileged: true
        container_name: magma-oai-nr-ue
        environment:
            RFSIMULATOR: 192.168.60.154
            FULL_IMSI: '724990000000008'
            FULL_KEY: '465B5CE8B199B49FAA5F0A2EE238A6BC'
            OPC: 'E8ED289DEBA952E4283B54E88E6183CA'
            DNN: 'internet'
            NSSAI_SST: 1
            NSSAI_SD: 1
            USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        depends_on:
            - oai-gnb
        network_mode: host
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
