# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define :oai_gnb_ue_sim, autostart: false do |oai_gnb_ue_sim|
    oai_gnb_ue_sim.vm.hostname = "oai-gnb-ue-sim"
    oai_gnb_ue_sim.vm.network "private_network", ip: "192.168.60.154", nic_type: "82540EM"
    oai_gnb_ue_sim.vm.network "private_network", ip: "192.168.129.52", nic_type: "82540EM"

    oai_gnb_ue_sim.vm.provider "virtualbox" do |vb|
      vb.name = "oai-gnb-ue-sim"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "6144"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end
end
